In [145]:
import numpy as np
from matplotlib import pyplot as plt

In [146]:
ifile = open("attitude-mike70507kilo/test.txt", "r")
lines = ifile.readlines()
ifile.close()

In [147]:
catalog = []
for line in lines:
    try:
        vals = [float(x.strip()) for x in line.strip().split(",")]
        catalog.append(vals)
    except:
        print("Problem with line " + line)

Problem with line 



In [148]:
len(catalog), catalog[0]

(2500,
 [0.4246963852085621,
  -0.1078184418823168,
  0.898892743313044,
  549.8530678073147])

In [149]:
def read_samples(lines):
    result = []
    for line in lines:
        try:
            [first,rest] = line.strip().split(":")
            idx = int(first.strip())
            vals = [float(x.strip()) for x in rest.strip().split(",")]
            result.append((idx, vals))
        except:
            print("Problem with line " + line)
    return result

In [150]:
samps = read_samples(open("sample.txt").readlines())

Problem with line Ticket please:

Problem with line   ID : X,		Y,		Z

Problem with line --------------------------------------------------

Problem with line 

Problem with line Timeout, Bye



In [151]:
samp_map = np.array([s[1][:3] for s in samps])
samp_map

array([[ 1.78608e-01,  9.83582e-01,  2.58180e-02],
       [-2.34670e-02,  9.98632e-01, -4.67270e-02],
       [ 1.64927e-01,  9.83500e-01, -7.43480e-02],
       [ 1.13964e-01,  9.86920e-01,  1.14018e-01],
       [ 4.30150e-02,  9.94060e-01, -9.99740e-02],
       [ 7.82020e-02,  9.90142e-01,  1.16203e-01],
       [-7.15160e-02,  9.96189e-01,  4.99290e-02],
       [ 1.43011e-01,  9.79738e-01,  1.40222e-01],
       [ 1.46123e-01,  9.85222e-01, -8.93640e-02],
       [-1.78620e-02,  9.96373e-01,  8.32020e-02],
       [-1.44940e-02,  9.95435e-01, -9.43340e-02],
       [-8.20000e-05,  9.94907e-01, -1.00793e-01],
       [-1.37770e-02,  9.91742e-01, -1.27505e-01],
       [-3.11010e-02,  9.89939e-01, -1.38037e-01],
       [ 1.12983e-01,  9.89126e-01, -9.41580e-02],
       [-3.69290e-02,  9.94859e-01,  9.42980e-02],
       [ 1.26992e-01,  9.82975e-01,  1.32787e-01],
       [-2.16440e-02,  9.99478e-01,  2.40000e-02]])

In [156]:
match_map = np.array([catalog[s[0]][:3] for s in samps])
match_map

array([[ 9.68503784e-01,  8.38823843e-02,  2.34444379e-01],
       [ 9.98878702e-01,  4.18924891e-02,  2.20535321e-02],
       [ 9.79219626e-01, -1.32496306e-02,  2.02369393e-01],
       [ 9.65723648e-01,  1.82732852e-01,  1.84354386e-01],
       [ 9.96577932e-01, -2.08811179e-02,  7.99775201e-02],
       [ 9.69770094e-01,  1.92407945e-01,  1.50083802e-01],
       [ 9.89589935e-01,  1.43687909e-01, -8.09604452e-03],
       [ 9.55756044e-01,  2.05837176e-01,  2.10146239e-01],
       [ 9.82404915e-01, -2.00047168e-02,  1.85688974e-01],
       [ 9.84683768e-01,  1.69480494e-01,  4.09174653e-02],
       [ 9.99762114e-01,  7.23128804e-05,  2.18107861e-02],
       [ 9.99339769e-01, -1.61437145e-02,  3.25485256e-02],
       [ 9.99148580e-01, -3.50174000e-02,  2.18150393e-02],
       [ 9.99130971e-01, -4.15994028e-02,  2.60606982e-03],
       [ 9.87772158e-01, -1.90551901e-02,  1.54735465e-01],
       [ 9.82326707e-01,  1.85143523e-01,  2.74975863e-02],
       [ 9.59940943e-01,  2.04206022e-01

In [157]:
rot_mat = np.dot(np.linalg.pinv(match_map), samp_map)
rot_mat

array([[-0.03853851,  0.99463625, -0.0931032 ],
       [-0.1408438 ,  0.08804741,  0.98674686],
       [ 0.97976675,  0.05414869,  0.12747946]])

In [158]:
tmp_err = samp_map - np.dot(match_map, rot_mat)
tmp_err, np.sum(tmp_err*tmp_err)

(array([[-1.95379973e-03,  1.92542328e-04,  3.33127508e-03],
        [-6.78721880e-04,  2.28336282e-04,  2.12314481e-03],
        [ 2.52373554e-03, -2.58781695e-04,  4.09656729e-03],
        [-3.70595753e-03,  3.04545321e-04,  1.17491646e-04],
        [ 1.21339182e-04,  3.35310488e-04,  3.21947701e-03],
        [-4.37215766e-03,  5.05644430e-04, -2.49884373e-03],
        [-5.20889097e-03, -3.05982387e-04,  1.31147167e-03],
        [ 2.94100634e-03, -3.94184900e-04, -6.92574635e-04],
        [-7.65999859e-04, -2.06994413e-04, -1.83090115e-03],
        [ 3.86695090e-03, -1.67119215e-04,  2.42872362e-03],
        [ 2.67604564e-03, -1.52034597e-04, -4.10473379e-03],
        [ 4.26736206e-03,  5.86389614e-04,  4.02921755e-03],
        [-1.57693453e-03, -1.45463800e-04, -2.70873371e-03],
        [-1.00833779e-03, -3.11280326e-04, -4.29885352e-03],
        [-3.23820080e-03, -4.89602167e-05, -3.11619970e-03],
        [ 6.35051240e-05,  1.08793349e-05, -4.39412736e-04],
        [ 4.76206699e-03

In [24]:
from quaternions import Quaternion

In [37]:
q = Quaternion.from_matrix(rot_mat)
q

In [38]:
q_comps = [q.w, q.x, q.y, q.z]
q_comps

[0.542445472221535,
 -0.42981194335017586,
 -0.49445981397525673,
 -0.5233152946856817]

In [39]:
", ".join([str(x) for x in q_comps])

'0.542445472221535, -0.42981194335017586, -0.49445981397525673, -0.5233152946856817'

In [40]:
np.dot(rot_mat, rot_mat.T)

array([[ 0.9994547 ,  0.00113377,  0.00423076],
       [ 0.00113377,  1.0012587 , -0.00743646],
       [ 0.00423076, -0.00743646,  0.97912598]])

In [41]:
new_rot,upper = np.linalg.qr(rot_mat)
new_rot, upper

(array([[-0.03890467,  0.99473722, -0.09478546],
        [-0.14218198,  0.08838134,  0.98588692],
        [ 0.98907569,  0.05183239,  0.13799526]]),
 array([[ 0.99058825,  0.0023424 , -0.01058864],
        [ 0.        ,  0.99999011,  0.00120436],
        [ 0.        ,  0.        ,  0.99923722]]))

In [42]:
samp_map - np.dot(match_map, new_rot)

array([[-3.66934841e-03,  6.09785669e-04,  2.56732026e-03],
       [-4.62206534e-04,  1.64572606e-04,  3.60763928e-03],
       [ 9.80714215e-04,  1.15518811e-04,  3.60440556e-03],
       [-4.82396002e-03,  5.73037473e-04, -3.93981331e-05],
       [-2.86200860e-04,  4.26910069e-04,  4.03700229e-03],
       [-5.15670893e-03,  6.91116254e-04, -2.28022371e-03],
       [-4.57889573e-03, -4.72635424e-04,  3.18492502e-03],
       [ 1.61017726e-03, -7.26596263e-05, -1.11758614e-03],
       [-2.16161749e-03,  1.30603251e-04, -2.14810542e-03],
       [ 4.07340140e-03, -2.28359483e-04,  3.80068740e-03],
       [ 2.83918119e-03, -2.02485069e-04, -2.65216344e-03],
       [ 4.30868610e-03,  5.66268523e-04,  5.35421665e-03],
       [-1.46101962e-03, -1.84125247e-04, -1.28741533e-03],
       [-7.22422240e-04, -3.92235898e-04, -2.68122725e-03],
       [-4.34243840e-03,  2.16080765e-04, -3.09805742e-03],
       [ 4.14977272e-04, -8.64376630e-05,  1.08317588e-03],
       [ 3.60073939e-03,  9.30398212e-05

In [166]:
np.dot(q_comps, q_comps)

0.9973348022685063

In [167]:
new_q = Quaternion.from_matrix(new_rot)
new_q_comps = [new_q.w, new_q.x, new_q.y, new_q.z]
new_q_comps

[0.5448559262263594,
 -0.4285786780917938,
 -0.4973154807761427,
 -0.5216604728379377]

In [46]:
np.dot(new_q_comps, new_q_comps)

1.0000000000000002

In [47]:
", ".join([str(x) for x in new_q_comps])

'0.5448559262263594, -0.4285786780917938, -0.4973154807761427, -0.5216604728379377'

In [51]:
match_map.T - np.dot(new_rot, samp_map.T)

array([[-5.05986665e-04,  1.60263265e-04,  2.64888752e-04,
        -7.61430660e-04, -5.31487593e-05, -1.10423119e-03,
         5.93892199e-04,  2.89897351e-05, -4.17622101e-04,
         7.45881937e-04,  6.04903131e-05,  1.11841543e-04,
         4.28748995e-06,  1.07924684e-04, -6.77535529e-04,
         2.04796642e-04, -3.34019655e-04,  5.14664038e-04],
       [-3.10669635e-03, -3.63698697e-03, -3.42430613e-03,
        -6.97683888e-04, -4.05845125e-03,  1.45376988e-03,
        -3.74924022e-03,  1.33717351e-03,  1.79890310e-03,
        -3.14770102e-03,  3.03630956e-03, -4.71608223e-03,
         1.07778852e-03,  2.57533779e-03,  2.41782031e-03,
        -1.00124717e-03,  4.47238546e-03, -3.92070327e-03],
       [ 3.24337862e-03, -4.92100619e-05, -1.47337908e-03,
         4.74699641e-03, -2.96140633e-04,  5.37921327e-03,
         4.11386771e-03, -1.43459947e-03,  2.42766218e-03,
        -4.54154270e-03, -2.43168382e-03, -5.02982422e-03,
         1.63225984e-03,  1.10485744e-03,  4.71131749e

In [52]:
e = samp_map - np.dot(match_map, new_rot)
np.sum(e*e)

0.000349032138766286

In [101]:
def fit_without_rows(i, s_in = samp_map, m_in = match_map):
    s = s_in.copy()
    m = m_in.copy()
    if i is not None:
        s = np.vstack([s[:i,:], s[(i+1):,:]])
        m = np.vstack([m[:i,:], m[(i+1):,:]])
    rot = np.dot(np.linalg.pinv(m), s)
    (rot, _) = np.linalg.qr(rot)
    errs = s - np.dot(m, rot)
    sqrd_mag = np.sum(errs*errs)
    return (rot, errs, sqrd_mag)
        

In [129]:
def best_to_remove(s = samp_map, m = match_map):
    (r,errs, err) = fit_without_rows(None, s_in = s, m_in = m)
    best = err
    best_i = None
    for i in range(s.shape[0]):
        (r, errs, err) = fit_without_rows(i, s_in = s, m_in = m)
        if err < best:
            best = err
            best_i = i
    return (best, int(best_i))

In [132]:
def trim_down_n(n):
    s = samp_map.copy()
    m = match_map.copy()
    for i in range(n):
        (best, to_remove) = best_to_remove(s=s,m=m)
        print("(best, to_remove) is " + str((best, to_remove)) +", matrix dims are " + str(s.shape) + str(m.shape))
        if to_remove is None:
            print("Exit loop on iter " + str(n))
            break
        s = np.vstack([s[:to_remove,:], s[int(to_remove+1):,:]])
        m = np.vstack([m[:to_remove,:], m[int(to_remove+1):,:]])
        print("after removing row " + str(to_remove) + " matrix dims are " + str(s.shape) + str(m.shape))
    (rot, errs, sqrd_mag) = fit_without_rows(None, s_in=s, m_in=m)
    return (rot,s,m,sqrd_mag)

In [133]:
trim_down_n(5)

(best, to_remove) is (0.00030049942640474476, 11), matrix dims are (18, 3)(18, 3)
after removing row 11 matrix dims are (17, 3)(17, 3)
(best, to_remove) is (0.0002594271725429861, 9), matrix dims are (17, 3)(17, 3)
after removing row 9 matrix dims are (16, 3)(16, 3)
(best, to_remove) is (0.00022635295845244976, 14), matrix dims are (16, 3)(16, 3)
after removing row 14 matrix dims are (15, 3)(15, 3)
(best, to_remove) is (0.00019005199644083653, 14), matrix dims are (15, 3)(15, 3)
after removing row 14 matrix dims are (14, 3)(14, 3)
(best, to_remove) is (0.00016706368495004212, 9), matrix dims are (14, 3)(14, 3)
after removing row 9 matrix dims are (13, 3)(13, 3)


(array([[-0.04032363,  0.99459961, -0.09563271],
        [-0.14691554,  0.08876853,  0.98515784],
        [ 0.98832678,  0.05377507,  0.14254267]]),
 array([[ 0.178608,  0.983582,  0.025818],
        [-0.023467,  0.998632, -0.046727],
        [ 0.164927,  0.9835  , -0.074348],
        [ 0.113964,  0.98692 ,  0.114018],
        [ 0.043015,  0.99406 , -0.099974],
        [ 0.078202,  0.990142,  0.116203],
        [-0.071516,  0.996189,  0.049929],
        [ 0.143011,  0.979738,  0.140222],
        [ 0.146123,  0.985222, -0.089364],
        [-0.013777,  0.991742, -0.127505],
        [-0.031101,  0.989939, -0.138037],
        [ 0.112983,  0.989126, -0.094158],
        [-0.036929,  0.994859,  0.094298]]),
 array([[ 0.96850378,  0.08388238,  0.23444438],
        [ 0.9988787 ,  0.04189249,  0.02205353],
        [ 0.97921963, -0.01324963,  0.20236939],
        [ 0.96572365,  0.18273285,  0.18435439],
        [ 0.99657793, -0.02088112,  0.07997752],
        [ 0.96977009,  0.19240795,  0.1500838

In [123]:
(rot, _, _, err) = trim_down_n(0)
rot, err, np.dot(rot.T, rot)

(array([[-0.03890467,  0.99473722, -0.09478546],
        [-0.14218198,  0.08838134,  0.98588692],
        [ 0.98907569,  0.05183239,  0.13799526]]),
 0.000349032138766286,
 array([[ 1.00000000e+00,  2.75830353e-16, -1.37508127e-17],
        [ 2.75830353e-16,  1.00000000e+00, -3.17253610e-16],
        [-1.37508127e-17, -3.17253610e-16,  1.00000000e+00]]))

In [124]:
fit_without_rows(None)

(array([[-0.03890467,  0.99473722, -0.09478546],
        [-0.14218198,  0.08838134,  0.98588692],
        [ 0.98907569,  0.05183239,  0.13799526]]),
 array([[-3.66934841e-03,  6.09785669e-04,  2.56732026e-03],
        [-4.62206534e-04,  1.64572606e-04,  3.60763928e-03],
        [ 9.80714215e-04,  1.15518811e-04,  3.60440556e-03],
        [-4.82396002e-03,  5.73037473e-04, -3.93981331e-05],
        [-2.86200860e-04,  4.26910069e-04,  4.03700229e-03],
        [-5.15670893e-03,  6.91116254e-04, -2.28022371e-03],
        [-4.57889573e-03, -4.72635424e-04,  3.18492502e-03],
        [ 1.61017726e-03, -7.26596263e-05, -1.11758614e-03],
        [-2.16161749e-03,  1.30603251e-04, -2.14810542e-03],
        [ 4.07340140e-03, -2.28359483e-04,  3.80068740e-03],
        [ 2.83918119e-03, -2.02485069e-04, -2.65216344e-03],
        [ 4.30868610e-03,  5.66268523e-04,  5.35421665e-03],
        [-1.46101962e-03, -1.84125247e-04, -1.28741533e-03],
        [-7.22422240e-04, -3.92235898e-04, -2.68122725e-03

In [125]:
len(samp_map)

18

In [134]:
trim_down_n(15)

(best, to_remove) is (0.00030049942640474476, 11), matrix dims are (18, 3)(18, 3)
after removing row 11 matrix dims are (17, 3)(17, 3)
(best, to_remove) is (0.0002594271725429861, 9), matrix dims are (17, 3)(17, 3)
after removing row 9 matrix dims are (16, 3)(16, 3)
(best, to_remove) is (0.00022635295845244976, 14), matrix dims are (16, 3)(16, 3)
after removing row 14 matrix dims are (15, 3)(15, 3)
(best, to_remove) is (0.00019005199644083653, 14), matrix dims are (15, 3)(15, 3)
after removing row 14 matrix dims are (14, 3)(14, 3)
(best, to_remove) is (0.00016706368495004212, 9), matrix dims are (14, 3)(14, 3)
after removing row 9 matrix dims are (13, 3)(13, 3)
(best, to_remove) is (0.00014282018631942868, 2), matrix dims are (13, 3)(13, 3)
after removing row 2 matrix dims are (12, 3)(12, 3)
(best, to_remove) is (0.00012068161937321926, 4), matrix dims are (12, 3)(12, 3)
after removing row 4 matrix dims are (11, 3)(11, 3)
(best, to_remove) is (0.000101878946040047, 3), matrix dims are 

(array([[-0.04150825,  0.99477708, -0.09325031],
        [-0.12598291,  0.08737484,  0.98817708],
        [ 0.99116365,  0.05276544,  0.12169814]]),
 array([[ 0.143011,  0.979738,  0.140222],
        [ 0.146123,  0.985222, -0.089364],
        [-0.036929,  0.994859,  0.094298]]),
 array([[ 0.95575604,  0.20583718,  0.21014624],
        [ 0.98240491, -0.02000472,  0.18568897],
        [ 0.98232671,  0.18514352,  0.02749759]]),
 8.828059593039942e-07)

In [113]:
(r_t, s_t, m_t, stuff1) = trim_down_n(15)

(best, to_remove) is (0.00030049942640474476, 11), matrix dims are (18, 3)(18, 3)
(best, to_remove) is (0.0002773796480733462, 10), matrix dims are (17, 3)(17, 3)
(best, to_remove) is (0.0002492096963709992, 9), matrix dims are (16, 3)(16, 3)
(best, to_remove) is (0.0002298234034896119, 8), matrix dims are (15, 3)(15, 3)
(best, to_remove) is (0.00020872279248238952, 7), matrix dims are (14, 3)(14, 3)
(best, to_remove) is (0.0002075762471373217, 6), matrix dims are (13, 3)(13, 3)
(best, to_remove) is (0.00018373475809039318, 5), matrix dims are (12, 3)(12, 3)
(best, to_remove) is (0.00017952601558046753, 2), matrix dims are (11, 3)(11, 3)
(best, to_remove) is (0.00015106479264604395, 2), matrix dims are (10, 3)(10, 3)
(best, to_remove) is (0.00012352553515795547, 2), matrix dims are (9, 3)(9, 3)
(best, to_remove) is (0.00012352553515795547, 2), matrix dims are (9, 3)(9, 3)
(best, to_remove) is (0.00012352553515795547, 2), matrix dims are (9, 3)(9, 3)
(best, to_remove) is (0.000123525535

In [114]:
s_t, np.vstack([s_t[:2,:], s_t[3:,:]])

(array([[-2.34670e-02,  9.98632e-01, -4.67270e-02],
        [ 1.13964e-01,  9.86920e-01,  1.14018e-01],
        [ 7.82020e-02,  9.90142e-01,  1.16203e-01],
        [ 1.43011e-01,  9.79738e-01,  1.40222e-01],
        [-1.78620e-02,  9.96373e-01,  8.32020e-02],
        [-8.20000e-05,  9.94907e-01, -1.00793e-01],
        [-3.11010e-02,  9.89939e-01, -1.38037e-01],
        [-3.69290e-02,  9.94859e-01,  9.42980e-02],
        [-2.16440e-02,  9.99478e-01,  2.40000e-02]]),
 array([[-2.34670e-02,  9.98632e-01, -4.67270e-02],
        [ 1.13964e-01,  9.86920e-01,  1.14018e-01],
        [ 1.43011e-01,  9.79738e-01,  1.40222e-01],
        [-1.78620e-02,  9.96373e-01,  8.32020e-02],
        [-8.20000e-05,  9.94907e-01, -1.00793e-01],
        [-3.11010e-02,  9.89939e-01, -1.38037e-01],
        [-3.69290e-02,  9.94859e-01,  9.42980e-02],
        [-2.16440e-02,  9.99478e-01,  2.40000e-02]]))

In [135]:
new_q_t = Quaternion.from_matrix(r_t)
new_q_comps_t = [new_q_t.w, new_q_t.x, new_q_t.y, new_q_t.z]
new_q_comps_t

[0.5451220856425634,
 -0.4286602420290858,
 -0.4967104439763744,
 -0.5218917928968233]

In [136]:
", ".join([str(x) for x in new_q_comps_t])

'0.5451220856425634, -0.4286602420290858, -0.4967104439763744, -0.5218917928968233'

In [162]:
dir(Quaternion)

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 'almost_equal',
 'average',
 'conjugate',
 'distance',
 'dot',
 'from_axis_angle',
 'from_euler',
 'from_matrix',
 'from_quaternion',
 'from_rotation_vector',
 'from_translation',
 'get_euler',
 'get_rotation_matrix',
 'get_rotation_vector',
 'get_xyz_vector',
 'inverse',
 'norm',
 'unit',
 'vector_average']

In [141]:
def quat_comps(q_in):
    return [q_in.w, q_in.x, q_in.y, q_in.z]

In [164]:
wild_guess = Quaternion(0.5,0.5,0.5,0.5) * new_q
quat_comps(wild_guess), wild_guess.norm()

([0.9962052789661168,
  0.04596612803638528,
  0.07031112009818027,
  -0.022770674647963618],
 1.0)

In [144]:
", ".join([str(x) for x in quat_comps(wild_guess)])

'0.9962052789661168, 0.04596612803638528, 0.07031112009818027, -0.022770674647963618'

In [171]:
def err_calc(q_in):
    q = q_in/q_in.norm()
    m = q.get_rotation_matrix()
    e_mat = samp_map - np.dot(match_map, rot)
    return np.sum(e_mat * e_mat)

In [172]:
err_calc(q)

0.000349032138766286

In [177]:
err_calc(new_q), new_q.unit(), np.random.random() * 0.1

(0.000349032138766286,
 0.09331869350937039)

In [181]:
curr = new_q.unit()
from random import randrange
best_err = err_calc(curr)
for i in range(10000):
    stepsize = (np.random.random() - 0.5) * 1.0e-5
    axis = randrange(3)
    if i % 1000 == 0:
        print("On iter " + str(i))
    tmp = curr.unit()
    if axis == 0:
        tmp.x += stepsize
    elif axis == 1:
        tmp.y += stepsize
    else:
        tmp.z += stepsize
    tmp = tmp.unit()
    if err_calc(tmp) < best_err:
        best_err = err_calc(tmp)
        curr = tmp.unit()
        print("iter" + str(i) + "Err is now " + str(best_err) + ", q is " + str(quat_comps(curr)))

On iter 0
On iter 1000
On iter 2000
On iter 3000
On iter 4000
On iter 5000
On iter 6000
On iter 7000
On iter 8000
On iter 9000
