In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [10]:
ifile = open("attitude-mike70507kilo/test.txt", "r")
lines = ifile.readlines()
ifile.close()

In [13]:
catalog = []
for line in lines:
    try:
        vals = [float(x.strip()) for x in line.strip().split(",")]
        catalog.append(vals)
    except:
        print("Problem with line " + line)

Problem with line 



In [14]:
len(catalog), catalog[0]

(2500,
 [0.4246963852085621,
  -0.1078184418823168,
  0.898892743313044,
  549.8530678073147])

In [15]:
def read_samples(lines):
    result = []
    for line in lines:
        try:
            [first,rest] = line.strip().split(":")
            idx = int(first.strip())
            vals = [float(x.strip()) for x in rest.strip().split(",")]
            result.append((idx, vals))
        except:
            print("Problem with line " + line)
    return result

In [16]:
samps = read_samples(open("sample.txt").readlines())

Problem with line Ticket please:

Problem with line   ID : X,		Y,		Z

Problem with line --------------------------------------------------

Problem with line 



In [17]:
samp_map = np.array([s[1][:3] for s in samps])
samp_map

array([[ 1.78608e-01,  9.83582e-01,  2.58180e-02],
       [-2.34670e-02,  9.98632e-01, -4.67270e-02],
       [ 1.64927e-01,  9.83500e-01, -7.43480e-02],
       [ 1.13964e-01,  9.86920e-01,  1.14018e-01],
       [ 4.30150e-02,  9.94060e-01, -9.99740e-02],
       [ 7.82020e-02,  9.90142e-01,  1.16203e-01],
       [-7.15160e-02,  9.96189e-01,  4.99290e-02],
       [ 1.43011e-01,  9.79738e-01,  1.40222e-01],
       [ 1.46123e-01,  9.85222e-01, -8.93640e-02],
       [-1.78620e-02,  9.96373e-01,  8.32020e-02],
       [-1.44940e-02,  9.95435e-01, -9.43340e-02],
       [-8.20000e-05,  9.94907e-01, -1.00793e-01],
       [-1.37770e-02,  9.91742e-01, -1.27505e-01],
       [-3.11010e-02,  9.89939e-01, -1.38037e-01],
       [ 1.12983e-01,  9.89126e-01, -9.41580e-02],
       [-3.69290e-02,  9.94859e-01,  9.42980e-02],
       [ 1.26992e-01,  9.82975e-01,  1.32787e-01],
       [-2.16440e-02,  9.99478e-01,  2.40000e-02]])

In [18]:
match_map = np.array([catalog[s[0]][:3] for s in samps])
match_map

array([[ 9.68503784e-01,  8.38823843e-02,  2.34444379e-01],
       [ 9.98878702e-01,  4.18924891e-02,  2.20535321e-02],
       [ 9.79219626e-01, -1.32496306e-02,  2.02369393e-01],
       [ 9.65723648e-01,  1.82732852e-01,  1.84354386e-01],
       [ 9.96577932e-01, -2.08811179e-02,  7.99775201e-02],
       [ 9.69770094e-01,  1.92407945e-01,  1.50083802e-01],
       [ 9.89589935e-01,  1.43687909e-01, -8.09604452e-03],
       [ 9.55756044e-01,  2.05837176e-01,  2.10146239e-01],
       [ 9.82404915e-01, -2.00047168e-02,  1.85688974e-01],
       [ 9.84683768e-01,  1.69480494e-01,  4.09174653e-02],
       [ 9.99762114e-01,  7.23128804e-05,  2.18107861e-02],
       [ 9.99339769e-01, -1.61437145e-02,  3.25485256e-02],
       [ 9.99148580e-01, -3.50174000e-02,  2.18150393e-02],
       [ 9.99130971e-01, -4.15994028e-02,  2.60606982e-03],
       [ 9.87772158e-01, -1.90551901e-02,  1.54735465e-01],
       [ 9.82326707e-01,  1.85143523e-01,  2.74975863e-02],
       [ 9.59940943e-01,  2.04206022e-01

In [21]:
rot_mat = np.dot(np.linalg.pinv(match_map), samp_map)
rot_mat

array([[-0.03853851,  0.99463625, -0.0931032 ],
       [-0.1408438 ,  0.08804741,  0.98674686],
       [ 0.97976675,  0.05414869,  0.12747946]])

In [23]:
samp_map - np.dot(match_map, rot_mat)

array([[-1.95379973e-03,  1.92542328e-04,  3.33127508e-03],
       [-6.78721880e-04,  2.28336282e-04,  2.12314481e-03],
       [ 2.52373554e-03, -2.58781695e-04,  4.09656729e-03],
       [-3.70595753e-03,  3.04545321e-04,  1.17491646e-04],
       [ 1.21339182e-04,  3.35310488e-04,  3.21947701e-03],
       [-4.37215766e-03,  5.05644430e-04, -2.49884373e-03],
       [-5.20889097e-03, -3.05982387e-04,  1.31147167e-03],
       [ 2.94100634e-03, -3.94184900e-04, -6.92574635e-04],
       [-7.65999859e-04, -2.06994413e-04, -1.83090115e-03],
       [ 3.86695090e-03, -1.67119215e-04,  2.42872362e-03],
       [ 2.67604564e-03, -1.52034597e-04, -4.10473379e-03],
       [ 4.26736206e-03,  5.86389614e-04,  4.02921755e-03],
       [-1.57693453e-03, -1.45463800e-04, -2.70873371e-03],
       [-1.00833779e-03, -3.11280326e-04, -4.29885352e-03],
       [-3.23820080e-03, -4.89602167e-05, -3.11619970e-03],
       [ 6.35051240e-05,  1.08793349e-05, -4.39412736e-04],
       [ 4.76206699e-03, -1.86269398e-04

In [24]:
from quaternions import Quaternion

In [37]:
q = Quaternion.from_matrix(rot_mat)
q

In [38]:
q_comps = [q.w, q.x, q.y, q.z]
q_comps

[0.542445472221535,
 -0.42981194335017586,
 -0.49445981397525673,
 -0.5233152946856817]

In [39]:
", ".join([str(x) for x in q_comps])

'0.542445472221535, -0.42981194335017586, -0.49445981397525673, -0.5233152946856817'

In [40]:
np.dot(rot_mat, rot_mat.T)

array([[ 0.9994547 ,  0.00113377,  0.00423076],
       [ 0.00113377,  1.0012587 , -0.00743646],
       [ 0.00423076, -0.00743646,  0.97912598]])

In [41]:
new_rot,upper = np.linalg.qr(rot_mat)
new_rot, upper

(array([[-0.03890467,  0.99473722, -0.09478546],
        [-0.14218198,  0.08838134,  0.98588692],
        [ 0.98907569,  0.05183239,  0.13799526]]),
 array([[ 0.99058825,  0.0023424 , -0.01058864],
        [ 0.        ,  0.99999011,  0.00120436],
        [ 0.        ,  0.        ,  0.99923722]]))

In [42]:
samp_map - np.dot(match_map, new_rot)

array([[-3.66934841e-03,  6.09785669e-04,  2.56732026e-03],
       [-4.62206534e-04,  1.64572606e-04,  3.60763928e-03],
       [ 9.80714215e-04,  1.15518811e-04,  3.60440556e-03],
       [-4.82396002e-03,  5.73037473e-04, -3.93981331e-05],
       [-2.86200860e-04,  4.26910069e-04,  4.03700229e-03],
       [-5.15670893e-03,  6.91116254e-04, -2.28022371e-03],
       [-4.57889573e-03, -4.72635424e-04,  3.18492502e-03],
       [ 1.61017726e-03, -7.26596263e-05, -1.11758614e-03],
       [-2.16161749e-03,  1.30603251e-04, -2.14810542e-03],
       [ 4.07340140e-03, -2.28359483e-04,  3.80068740e-03],
       [ 2.83918119e-03, -2.02485069e-04, -2.65216344e-03],
       [ 4.30868610e-03,  5.66268523e-04,  5.35421665e-03],
       [-1.46101962e-03, -1.84125247e-04, -1.28741533e-03],
       [-7.22422240e-04, -3.92235898e-04, -2.68122725e-03],
       [-4.34243840e-03,  2.16080765e-04, -3.09805742e-03],
       [ 4.14977272e-04, -8.64376630e-05,  1.08317588e-03],
       [ 3.60073939e-03,  9.30398212e-05

In [43]:
np.dot(q_comps, q_comps)

0.9973348022685063

In [49]:
new_q = Quaternion.from_matrix(new_rot)
new_q_comps = [new_q.w, new_q.x, new_q.y, new_q.z]
new_q_comps

[0.5448559262263594,
 -0.4285786780917938,
 -0.4973154807761427,
 -0.5216604728379377]

In [46]:
np.dot(new_q_comps, new_q_comps)

1.0000000000000002

In [47]:
", ".join([str(x) for x in new_q_comps])

'0.5448559262263594, -0.4285786780917938, -0.4973154807761427, -0.5216604728379377'

In [51]:
match_map.T - np.dot(new_rot, samp_map.T)

array([[-5.05986665e-04,  1.60263265e-04,  2.64888752e-04,
        -7.61430660e-04, -5.31487593e-05, -1.10423119e-03,
         5.93892199e-04,  2.89897351e-05, -4.17622101e-04,
         7.45881937e-04,  6.04903131e-05,  1.11841543e-04,
         4.28748995e-06,  1.07924684e-04, -6.77535529e-04,
         2.04796642e-04, -3.34019655e-04,  5.14664038e-04],
       [-3.10669635e-03, -3.63698697e-03, -3.42430613e-03,
        -6.97683888e-04, -4.05845125e-03,  1.45376988e-03,
        -3.74924022e-03,  1.33717351e-03,  1.79890310e-03,
        -3.14770102e-03,  3.03630956e-03, -4.71608223e-03,
         1.07778852e-03,  2.57533779e-03,  2.41782031e-03,
        -1.00124717e-03,  4.47238546e-03, -3.92070327e-03],
       [ 3.24337862e-03, -4.92100619e-05, -1.47337908e-03,
         4.74699641e-03, -2.96140633e-04,  5.37921327e-03,
         4.11386771e-03, -1.43459947e-03,  2.42766218e-03,
        -4.54154270e-03, -2.43168382e-03, -5.02982422e-03,
         1.63225984e-03,  1.10485744e-03,  4.71131749e

In [52]:
e = samp_map - np.dot(match_map, new_rot)
np.sum(e*e)

0.000349032138766286

In [78]:
def fit_without_rows(i, s_in = samp_map, m_in = match_map):
    s = s_in
    m = m_in
    if i is not None:
        s = np.vstack([s[:i,:], s[(i+1):,:]])
        m = np.vstack([m[:i,:], m[(i+1):,:]])
    rot = np.dot(np.linalg.pinv(m), s)
    (rot, _) = np.linalg.qr(rot)
    errs = s - np.dot(m, rot)
    sqrd_mag = np.sum(errs*errs)
    return (rot, errs, sqrd_mag)
        

In [79]:
def best_to_remove(s = samp_map, m = match_map):
    (r,errs, err) = fit_without_rows(None, s_in = s, m_in = m)
    best = err
    best_i = None
    for i in range(s.shape[0]):
        (r, errs, err) = fit_without_rows(i, s_in = s, m_in = m)
        if err < best:
            best = err
            best_i = i
    return (best, i)

In [80]:
def trim_down_n(n):
    s = samp_map
    m = match_map
    for i in range(n):
        (best, to_remove) = best_to_remove(s,m)
        if to_remove is None:
            print("Exit loop on iter " + str(n))
            break
        s = np.vstack([s[:i,:], s[(i+1):,:]])
        m = np.vstack([m[:i,:], m[(i+1):,:]])
    (rot, errs, sqrd_mag) = fit_without_rows(None, s_in=s, m_in=m)
    return (rot,s,m,sqrd_mag)

In [81]:
trim_down_n(5)

(array([[-0.03881401,  0.99476273, -0.0945547 ],
        [-0.13472924,  0.0885521 ,  0.98691771],
        [ 0.99012196,  0.05104552,  0.13058657]]),
 array([[-2.34670e-02,  9.98632e-01, -4.67270e-02],
        [ 1.13964e-01,  9.86920e-01,  1.14018e-01],
        [ 7.82020e-02,  9.90142e-01,  1.16203e-01],
        [ 1.43011e-01,  9.79738e-01,  1.40222e-01],
        [-1.78620e-02,  9.96373e-01,  8.32020e-02],
        [-1.44940e-02,  9.95435e-01, -9.43340e-02],
        [-8.20000e-05,  9.94907e-01, -1.00793e-01],
        [-1.37770e-02,  9.91742e-01, -1.27505e-01],
        [-3.11010e-02,  9.89939e-01, -1.38037e-01],
        [ 1.12983e-01,  9.89126e-01, -9.41580e-02],
        [-3.69290e-02,  9.94859e-01,  9.42980e-02],
        [ 1.26992e-01,  9.82975e-01,  1.32787e-01],
        [-2.16440e-02,  9.99478e-01,  2.40000e-02]]),
 array([[ 9.98878702e-01,  4.18924891e-02,  2.20535321e-02],
        [ 9.65723648e-01,  1.82732852e-01,  1.84354386e-01],
        [ 9.69770094e-01,  1.92407945e-01,  1.50083

In [83]:
(rot, _, _, err) = trim_down_n(0)
rot, err, np.dot(rot.T, rot)

(array([[-0.03890467,  0.99473722, -0.09478546],
        [-0.14218198,  0.08838134,  0.98588692],
        [ 0.98907569,  0.05183239,  0.13799526]]),
 0.000349032138766286,
 array([[ 1.00000000e+00,  2.75830353e-16, -1.37508127e-17],
        [ 2.75830353e-16,  1.00000000e+00, -3.17253610e-16],
        [-1.37508127e-17, -3.17253610e-16,  1.00000000e+00]]))

In [70]:
fit_without_rows(None)

(array([[-0.03853851,  0.99463625, -0.0931032 ],
        [-0.1408438 ,  0.08804741,  0.98674686],
        [ 0.97976675,  0.05414869,  0.12747946]]),
 array([[-1.95379973e-03,  1.92542328e-04,  3.33127508e-03],
        [-6.78721880e-04,  2.28336282e-04,  2.12314481e-03],
        [ 2.52373554e-03, -2.58781695e-04,  4.09656729e-03],
        [-3.70595753e-03,  3.04545321e-04,  1.17491646e-04],
        [ 1.21339182e-04,  3.35310488e-04,  3.21947701e-03],
        [-4.37215766e-03,  5.05644430e-04, -2.49884373e-03],
        [-5.20889097e-03, -3.05982387e-04,  1.31147167e-03],
        [ 2.94100634e-03, -3.94184900e-04, -6.92574635e-04],
        [-7.65999859e-04, -2.06994413e-04, -1.83090115e-03],
        [ 3.86695090e-03, -1.67119215e-04,  2.42872362e-03],
        [ 2.67604564e-03, -1.52034597e-04, -4.10473379e-03],
        [ 4.26736206e-03,  5.86389614e-04,  4.02921755e-03],
        [-1.57693453e-03, -1.45463800e-04, -2.70873371e-03],
        [-1.00833779e-03, -3.11280326e-04, -4.29885352e-03